format = """
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$nodejs\
$c\
$java\
$python\
$php\
$rust\
$jobs\
$cmd_duration\
$line_break\
$character"""

[fill]
symbol = " "

[directory]
truncation_length = 3

[git_branch]
format = '[]($style) [$branch ]($style)'
style = "bold #737aa2" 

[git_status]
format = '([$all_status$ahead_behind ]($style))'
style = "bold #737aa2"

[git_metrics]
added_style = "bold #c3e88d"
deleted_style = "bold #c53b53"
format = "([+$added]($added_style) [-$deleted]($deleted_style))"
disabled = false

[c]
detect_extensions = ['c', 'h', 'cpp', 'hpp']
format = '[](#737aa2) [$version(-$name)](bold #737aa2) '

[java]
format = '[]($style) [$version]($style) '

[nodejs]
format = '[]($style) [$version]($style) '

[package]
format = '[󰏗]($style) [$version]($style) '

[php]
format = '[ ]($style) [$version]($style) '

[python]
format = '[](#41a6b5) [${pyenv_prefix}(${version})(\($virtualenv\))](bold #41a6b5) '

[rust]
format = '[](#ff9e64) [$version](bold #ff9e64) '

[jobs]
symbol = ' '
style = 'bold #4f76c7'
number_threshold = 1
format = '[$number$symbol]($style) '

[cmd_duration]
min_time = 500
style = 'bold #9d7cd8'
format = '[$duration]($style)'

[username]
format = '\[[$user]($style)\] '
