format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$nodejs\
$java\
$python\
$php\
$rust\
$jobs\
$cmd_duration\
$line_break\
$character"""

[fill]
symbol = " "

[directory]
truncation_length = 3

[c]
format = '\[📄 [$symbol($version(-$name))]($style)\]'

[git_branch]
format = '[]($style) [$branch ]($style)'
style = "bold #737aa2" 

[git_status]
format = '([$all_status$ahead_behind ]($style))'
style = "bold #737aa2"

[git_metrics]
added_style = "bold #c3e88d"
deleted_style = "bold #c53b53"
format = "([$added]($added_style) [-$deleted]($deleted_style))"
disabled = false

[java]
format = '☕ [$version]($style)'

[nodejs]
format = '🟢 [$version]($style)'

[package]
format = '📦 [$version]($style)'

[php]
format = '🐘 [$version]($style)'

[python]
format = '[](#41a6b5) [${pyenv_prefix}(${version})(\($virtualenv\))](bold #41a6b5)'

[rust]
format = '🦀 [$version]($style)'

[jobs]
symbol = ' '
style = 'bold #4f76c7'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = 'bold #737aa2'
format = '[$duration]($style)'

[username]
format = '\[[$user]($style)\] '
